version: '3.8'

services:
  user_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d user_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  user_service:
    build: .
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://user:password@user_db:5432/user_db
    depends_on:
      user_db:
        condition: service_healthy
    volumes:
      - ./app:/app/app:ro

volumes:
  user_db_data:
