version: '3.8'

services:
  loan_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: loan_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - loan_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d loan_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  loan_service:
    build: .
    ports:
      - "8003:8003"
    environment:
      DATABASE_URL: postgresql://user:password@loan_db:5432/loan_db
      USER_SERVICE_URL: http://host.docker.internal:8001
      BOOK_SERVICE_URL: http://host.docker.internal:8002
    depends_on:
      loan_db:
        condition: service_healthy
    volumes:
      - ./app:/app/app:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  loan_db_data:
