version: '3.8'

services:
  book_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: book_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - book_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d book_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  book_service:
    build: .
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql://user:password@book_db:5432/book_db
    depends_on:
      book_db:
        condition: service_healthy
    volumes:
      - ./app:/app/app:ro

volumes:
  book_db_data:
